/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import inventory.system.Stock;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seazer
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inentory
     */
    public Inventory() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pr_name = new javax.swing.JTextField();
        wholesale = new javax.swing.JTextField();
        quantities = new javax.swing.JTextField();
        add_time = new javax.swing.JTextField();
        supp_name = new javax.swing.JTextField();
        sell_price = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hard = new javax.swing.JComboBox<>();
        access = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 160, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selling Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Time");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantities");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Supplier Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Location");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 50));
        getContentPane().add(pr_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 210, 30));
        getContentPane().add(wholesale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 210, 30));
        getContentPane().add(quantities, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 30));
        getContentPane().add(add_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 210, 30));
        getContentPane().add(supp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 210, 30));
        getContentPane().add(sell_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 210, 30));
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Wholesale price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 160, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 200, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type of product");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 50));

        hard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware" }));
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hardMousePressed(evt);
            }
        });
        getContentPane().add(hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, 30));

        access.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        access.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accessory" }));
        access.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accessMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accessMousePressed(evt);
            }
        });
        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });
        getContentPane().add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 30));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 210, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 550, 190, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/system/99.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
FRONT a=new FRONT(); 
a.setVisible(true);
a.pack();
a.setLocationRelativeTo(null);
a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    
    
    private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accessActionPerformed

    private void accessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessMouseClicked
     // TODO add your handling code here:
    }//GEN-LAST:event_accessMouseClicked

    private void accessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_accessMouseEntered

    private void hardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseClicked
     this.hard.removeAllItems();
  hard.addItem("Hardware");
insertIntoHardware();   // TODO add your handling code here:
    }//GEN-LAST:event_hardMouseClicked

    private void hardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hardMouseEntered

    private void hardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMousePressed




// TODO add your handling code here:
    }//GEN-LAST:event_hardMousePressed

    private void accessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessMousePressed
access.removeAllItems();
    access.addItem("Accessory");
        insertIntoacsses();        // TODO add your handling code here:
    }//GEN-LAST:event_accessMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String pr_name=this.pr_name.getText();
            String ID=this.id.getText();
            
            String acc_name=this.access.getSelectedItem().toString();
            String hard_name=this.hard.getSelectedItem().toString(); 
            String add_time=this.add_time.getText();
            String sell=this.sell_price.getText();
            String wholesale=this.wholesale.getText();
            String quantities=this.quantities.getText();
            
            
            
            String supp_name=this.supp_name.getText();
            String array[]=supp_name.split(" ");
            String location=this.location.getText();
            String Description=this.jTextArea2.getText();
        
        
        if(pr_name.equals("")||ID.equals("")||(acc_name.equals("Accessory")&&hard_name.equals("Hardware"))||add_time.equals("")||sell.equals("")||wholesale.equals("")||quantities.equals("")||supp_name.equals("")||location.equals("")||Description.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Make sure all the fields are filled");
        }
        
        
        
        else{
        
        
        
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
            
            String g;
            if(hard.getSelectedIndex()==0&&access.getSelectedIndex()==0){
                
            }
            
            else{
            
            
            if(hard.getSelectedIndex()==0){
               g= " Accessory" +"("+ acc_name+")"; 
            }
            else{
              g= " Hardware" +"("+ hard_name+")"; }
            
            
            
            String str_stm1="insert into PRODUCT values('"+pr_name+"','"+g+"','"+add_time+"',"+sell+","+wholesale+","+quantities+",'"+ID+"')";
            String str_stm2="insert into LIST_OF_PRODUCT values('"+pr_name+"','"+quantities+"','"+"0"+"',"+quantities+","+sell+","+wholesale+",'"+Description+"','"+array[0]+"','"+array[1]+"','"+array[2]+"','"+ID+"')";
            String str_stm3="insert into SUPPLIER values('"+array[0]+"','"+array[1]+"','"+array[2]+"','"+location+"','"+pr_name+"',"+wholesale+",'"+ID+"' )";
            stmt.executeUpdate(str_stm1);
            stmt.executeUpdate(str_stm3);
            stmt.executeUpdate(str_stm2);
            

            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Added successfully");
              this.pr_name.setText("");
             this.add_time.setText("");
            this.sell_price.setText("");
           this.wholesale.setText("");
           this.quantities.setText("");
            this.id.setText("");
            this.access.setSelectedIndex(0);
            this.hard.setSelectedIndex(0);
            
            this.supp_name.setText("");
             this.jTextArea2.setText("");
            this.location.setText("");
            
            


// TODO add your handling code here:
        }} catch (Exception ex) {
            //Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.toString());
                
        }


        

        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    public void insertIntoacsses(){
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
            String stm= " select PIECE_TYPE from CLASS where TYPE_OF_PRODUCT= 'Accessory'";
            ResultSet rs= stmt.executeQuery(stm);
            while(rs.next()){
                String name=rs.getString("PIECE_TYPE");
                this.access.addItem(name);
            }
            
            con.commit();
            con.close();
            
            } 
       catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex.toString());
       }
    }
    
     public void insertIntoHardware(){
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
            String stm= " select PIECE_TYPE from CLASS where TYPE_OF_PRODUCT= 'Hardware'";
            ResultSet rs= stmt.executeQuery(stm);
            while(rs.next()){
                String name=rs.getString("PIECE_TYPE");
                this.hard.addItem(name);
            }
            
            con.commit();
            con.close();
            
            } 
       catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex.toString());
       }
    }
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> access;
    private javax.swing.JTextField add_time;
    private javax.swing.JComboBox<String> hard;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField pr_name;
    private javax.swing.JTextField quantities;
    private javax.swing.JTextField sell_price;
    private javax.swing.JTextField supp_name;
    private javax.swing.JTextField wholesale;
    // End of variables declaration//GEN-END:variables
}
