/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.system;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import oracle.jdbc.pool.OracleDataSource;
import inventory.system.EditProduct;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author seazer
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        load();
    }
    DefaultTableModel df;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsearsh = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        c_r = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsearsh.setToolTipText("You should Separates them by &&  like: mouse&&ameer yahia yaish");
        jsearsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearshActionPerformed(evt);
            }
        });
        jPanel1.add(jsearsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 320, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 160, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 170, 40));

        c_r.setBackground(new java.awt.Color(153, 76, 0));
        c_r.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_r.setForeground(new java.awt.Color(255, 255, 255));
        c_r.setText("Create Report");
        c_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rActionPerformed(evt);
            }
        });
        jPanel1.add(c_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 60));

        jButton1.setBackground(new java.awt.Color(153, 76, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit Selected Product");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 60));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 160, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Namber", "Product Name", "Remaning Quantity", "Soldout Quantity", "Original Quantity", "Price", "Wholeprice", "Supplier Name"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(5).setMaxWidth(70);
            table.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 930, 390));

        jButton5.setBackground(new java.awt.Color(153, 76, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Choose an item to describe");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 70));

        jButton7.setBackground(new java.awt.Color(153, 76, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Remove Selected Product ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 60));

        jButton2.setBackground(new java.awt.Color(153, 76, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Suppliers List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the name of the product ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 430, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/system/2013-07-13_070317_5951958.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 470, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/system/2013-07-13_070317_5951958.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 530));

        jButton6.setBackground(new java.awt.Color(153, 76, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Remove Selected Product ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

int selectedRowIndex;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    private void c_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rActionPerformed
        try {
            OracleDataSource ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("abood");
            ods.setPassword("123456");
            Connection con =ods.getConnection();
            JasperDesign jD;
            
            InputStream input=new FileInputStream(new File("Stock.Jrxml"));
            jD = JRXmlLoader.load(input);
            JasperReport jb;
            jb=JasperCompileManager.compileReport(jD);
            JasperPrint gp=JasperFillManager.fillReport(jb, null, con);
            OutputStream output=new FileOutputStream(new File("Stock.pdf"));
            JasperExportManager.exportReportToPdfStream(gp, output);
            output.close();
            input.close();
            
            
            




// TODO add your handling code here:
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c_rActionPerformed

    private void jsearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsearshActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
FRONT a=new FRONT(); 
a.setVisible(true);
a.pack();
a.setLocationRelativeTo(null);
a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked
EditProduct a=new EditProduct(); 
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   if (table.getSelectedRowCount()>1)
   {
       JOptionPane.showMessageDialog(null, "Please select one iteam");
   }
   else { 
        
        
        
        int index=table.getSelectedRow();
TableModel mod=table.getModel();
if(index<0){
   JOptionPane.showMessageDialog(null, "You didn't select an item to edit");
}
else{
String id=mod.getValueAt(index, 0).toString();
String pr=mod.getValueAt(index, 1).toString();
String soldout=mod.getValueAt(index, 3).toString();
String original=mod.getValueAt(index, 4).toString();
String supplier=mod.getValueAt(index, 7).toString();
String price=mod.getValueAt(index, 5).toString();
String wholeprice=mod.getValueAt(index,6 ).toString();
a.setVisible(true);
a.pack();
a.setLocationRelativeTo(null);
a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

a.id_product.setText(id);
  a.productName.setText(pr);

  a.soldout.setText(soldout);
  
  a.original.setText(original);
  a.supplier.setText(supplier);
  a.price.setText(price);
  a.wholeprice.setText(wholeprice);
}}
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked
String s;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Descriptions a=new Descriptions(); 
int row =this.table.getSelectedRow();
        if(row<0){
           JOptionPane.showMessageDialog(null, "You didn't select an item to Discribe"); 
        }
        else{     try {int t;
int index=table.getSelectedRow();
TableModel mod=table.getModel();
 s=  mod.getValueAt(index, 0).toString();
a.lolo.setText(s);
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
            String stm= " select * from LIST_OF_PRODUCT where ID="+s;
            ResultSet rs= stmt.executeQuery(stm);
        
         while(rs.next()){
            a.discribtion.setText(rs.getString(7));
                
            
         }
            con.commit();
            con.close();
            
            } catch (Exception ex) {
            //Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        } 









a.setVisible(true);

a.setLocationRelativeTo(null); 
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
       
        int []row=this.table.getSelectedRows();
        for(int i=0;i<row.length;i++){
             
             
             if(row[i]<0){
           JOptionPane.showMessageDialog(null, "You didn't select an item to edit"); 
        }
        else{
String colom=table.getModel().getValueAt(row[i], 0).toString();

        
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            
            String sql="DELETE  FROM LIST_OF_PRODUCT WHERE ID="+ colom;
            String sq2="DELETE  FROM PRODUCT WHERE ID="+ colom;
            String sq3="DELETE  FROM SUPPLIER WHERE PRODUCTID="+ colom;
            PreparedStatement stmt1=con.prepareStatement(sql);
            PreparedStatement stmt2=con.prepareStatement(sq2);
            PreparedStatement stmt3=con.prepareStatement(sq3);
            stmt1.execute();
            stmt2.execute();
            stmt3.execute();
             
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
        }   
             
             
             
             
        }
        
        
JOptionPane.showMessageDialog(null,"Delete successfully ");





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
load();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        
             // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
  
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 Statement s; 
        ResultSet rs;
        ResultSet re;
        int t;
       String searsh = this.jsearsh.getText();
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
             s=con.createStatement();
            String sears="SELECT * FROM list_of_product  WHERE PRODUCT_NAM LIKE '%"+searsh+"%' ";
            
            rs=s.executeQuery(sears);
          
           
            String m;
           
            ResultSetMetaData rd=rs.getMetaData();
            t=rd.getColumnCount();
            df= (DefaultTableModel)table.getModel();
            df.setRowCount(0);
          
            while(rs.next()){
                
                Vector b=new Vector();
                for(int i=0;i<t;i++){
                     b.add(rs.getString("ID"));
                    b.add(rs.getString("PRODUCT_NAM"));
                    b.add(rs.getString("REMAINING_QUANTITY"));
                    b.add(rs.getString("SOLDOUT_QUANTITY"));
                    b.add(rs.getString("ORIGINAL_QUANTITY"));
                    b.add(rs.getString("PRICE"));
                    b.add(rs.getString("WHOLEPRICE"));
                    m=rs.getString("SUPPLIER_FNAME")+" "+rs.getString("SUPPLIER_MNAME")+" "+ rs.getString("SUPPLIER_LNAME");
                    b.add(m);
                    
                  
                   
                
            }
                df.addRow(b);
                
                }
            con.commit();
            con.close();
                
            }
            
            
            
            
         catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
}
        
            
        
       
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
SuppliersInformation q=new SuppliersInformation();
try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
           
            String stm= " SELECT f_name,minit,last_name,provided_product,locations,wholeprice_of_provided_product FROM supplier ORDER BY  f_name,minit,last_name  ";
            ResultSet rs= stmt.executeQuery(stm);
             
            String supplier;
            
            int t;
            ResultSetMetaData rd=rs.getMetaData();
            t=rd.getColumnCount();
            df= (DefaultTableModel)q.table1.getModel();
            df.setRowCount(0);
            String s;
            while(rs.next()){
                Vector b=new Vector();
                for(int i=0;i<t;i++){
                    supplier= rs.getString("F_NAME")+" "+rs.getString("MINIT")+" "+rs.getString("LAST_NAME");
                   b.add(supplier);
                   b.add(rs.getString("PROVIDED_PRODUCT"));
                     b.add(rs.getString("LOCATIONS"));
                    b.add(rs.getString("WHOLEPRICE_OF_PROVIDED_PRODUCT"));
                    
                        
            }
                df.addRow(b);
                
            }
             String stm2="SELECT product_name,type_of_product,add_time,quantities FROM  PRODUCT ORDER BY type_of_product";
            ResultSet rm= stmt.executeQuery(stm2);
            int f;
            ResultSetMetaData rb=rm.getMetaData();
            f=rb.getColumnCount();
            df= (DefaultTableModel)q.pr.getModel();
            df.setRowCount(0);
            
            while(rm.next()){
                Vector b=new Vector();
                for(int i=0;i<f;i++){
                    
                   b.add(rm.getString("product_name"));
                   b.add(rm.getString("type_of_product"));
                     b.add(rm.getString("add_time"));
                    b.add(rm.getString("quantities"));
                    
                        
            }
                df.addRow(b);
                
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        
            

con.commit();
            con.close();
            q.setVisible(true);

q.setLocationRelativeTo(null); 
                
            }
            
            
            
            
         catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
}
        



       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
     
    
    
            
        
       
        
        
        
        
        
        
        
     
    
    
    
    
    
    
    
    
    
    
    
    
    
    public void load ()
     {
         int t;
       try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String surl="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(surl,"abood","123456");
            Statement stmt=con.createStatement();
            String stm= " select * from LIST_OF_PRODUCT";
            ResultSet rs= stmt.executeQuery(stm);
            ResultSetMetaData rd=rs.getMetaData();
            t=rd.getColumnCount();
            df= (DefaultTableModel)table.getModel();
            df.setRowCount(0);
            String s;
            while(rs.next()){
                Vector b=new Vector();
                for(int i=0;i<t;i++){
                     b.add(rs.getString("ID"));
                    b.add(rs.getString("PRODUCT_NAM"));
                    b.add(rs.getString("REMAINING_QUANTITY"));
                    b.add(rs.getString("SOLDOUT_QUANTITY"));
                    b.add(rs.getString("ORIGINAL_QUANTITY"));
                    b.add(rs.getString("PRICE"));
                    b.add(rs.getString("WHOLEPRICE"));
                    s=rs.getString("SUPPLIER_FNAME")+" "+rs.getString("SUPPLIER_MNAME")+" "+ rs.getString("SUPPLIER_LNAME");
                    b.add(s);
                   
                
            }
                df.addRow(b);
                
            }
            con.commit();
            con.close();
            
            } catch (Exception ex) {
            //Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
         
         
     }
     
     
     
     
     
     
     
     
     
     
     
     
    /**{
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_r;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jsearsh;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
